### PR TITLE
Prevent next/previous arrows from being announced by screen readers

### LINKED ISSUE #34: Accessibility: Hide left and right arrows from screen readers
Wrap the arrow characters in the previous and next buttons in `<span aria-hidden="true"></span>` so that they aren't announced by screen readers. These characters are decorative, and not required for comprehension, so that extra verbosity is unhelpful.

### PR DESCRIPTION
**Pull request by trymebytes**
Fixes #34 and #32

### CODE REVIEW

**Comment by joedolson** [comment]
I hope that this is just poorly titled; this should be preventing the next/previous *arrows* from being announced, not the buttons. I looked at the code, but that diff isn't exactly helpful.

**Comment by trymebytes** [comment]
@joedolson thanks for catching that, I have edited the title. The diff here is a compiled version of the js and css. I tested and found out that the arrows were still being read out but I have added another fix in this PR which solves it. 
To see the file changes in the source(uncompiled) file, follow https://github.com/kamranahmedse/driver.js/pull/460/commits/fe8ad69dcef1a56c42bc50b2d53b5ca07c706ad7

**Comment by akirk** [comment]
I am not sure the PR is doing what it says. When I use Voiceover on macOS it says "Next right arrow", should it just say "Next"?

Screenshot 2023-12-22 at 12 18 38

**Review by akirk — APPROVED** [review]
Apologies, my local GlotPress snuck in its driver.js version without the fix. When I deactivate it, it works as proposed:

Screenshot 2023-12-22 at 12 29 41

**Pull request merged**
