### PR TITLE
Add a rich text editor

### LINKED ISSUE #5: Make it easier to edit the tour description HTML
We should load the classic editor or similar for editing the html.

### PR DESCRIPTION
**Pull request by akirk**
Fixes #5. You can even upload media:
rich-editor-tour

### CODE REVIEW

**Review by trymebytes — APPROVED** [review]
Tested and works!

**Comment by amieiro** [comment]
It works fine for me. 

A weird behavior: if I copy and paste the text below (with bold and italic text) in the same or in different editor, it adds some weird symbols **after saving**. I suppose it is related with some codification problems.

image

image


image

**Comment by akirk** [comment]
@amieiro I fixed the line break issue, could you try to reproduce that again? Also, can it be fixed? Like can you delete the erroneous chars and things save properly after that?

**Comment by amieiro** [comment]
@akirk I was able to reproduce the problem. I share a GIF with the process to add the problem. I copy and paste the WYSIWYG text without saving before. After saving the copied text, it fails. 

tour

**Comment by akirk** [comment]
@amieiro I hope it's now fixed, can you try again? (It worked on FF, I could also reproduce it in Chrome)

**Comment by amieiro** [comment]
> @amieiro I hope it's now fixed, can you try again? (It worked on FF, I could also reproduce it in Chrome)

Now it works fine!

**Review by amieiro — APPROVED** [review]

**Pull request merged**
